### PR TITLE
Added quick endgame menu

### LINKED ISSUE #19: Main menu & end game menu screens

### PR DESCRIPTION
**Pull request by HarryThVu**

### CODE REVIEW

**Comment by arcangel25** [comment]
Make the titles more clear-- like "Leave the park" or "Be lonely again"

**Comment by PennyS8** [comment]
I changed the labels to be "give up on happyness" (exits the game) and "pursue happyness" (replay)

**Review by PennyS8 — APPROVED** [review]
LGTM

**Comment by PennyS8** [comment]
I'm not certain how to resolve merge conflicts @HarryThVu @n8hopp

**Comment by HarryThVu** [comment]
I can just redo this pull because this pull is simple enough to redo

**Comment by PennyS8** [comment]
We can definitely resolve the merge conflict, without redoing any work. Don't sweat it @HarryThVu

**Comment by n8hopp** [comment]
Fixed

**Comment by PennyS8** [comment]
TY Nate

**Pull request merged**
