### PR TITLE
Quick time events - ready to merge

### LINKED ISSUE #9: Implement quick time events

### PR DESCRIPTION
**Pull request by n8hopp**

### CODE REVIEW

**Comment by arcangel25** [comment]
Looks like the carousel QTE can only activate once-- if you play, exit, and then don't return until it stops moving again, the QTE won't work again. Is this on purpose?

**Comment by n8hopp** [comment]
Thank you for finding this @arcangel25! Should be fixed now

**Comment by arcangel25** [comment]
:)

**Review by arcangel25 — APPROVED** [review]
:)

**Pull request merged**
